### ISSUE TITLE
Stumptray covers part of the mode-line

### ISSUE THREAD

**Issue by ryuslash** [stumpwm/stumpwm-contrib#25] opened 2015-01-28 21:37 UTC
When right-aligning some text in the stumpwm mode-line and enabling stumptray the text will not be pushed to the left but instead is covered by the tray. It should be enough to have this in your `.stumpwmrc` for example:

``` lisp
(setf *screen-mode-line-format* "foo^>bar")
(stumptray:stumptray)
```

Here's a screenshot with vlc running:

![tray](https://cloud.githubusercontent.com/assets/132613/5947352/a710e93a-a73c-11e4-94f7-f009927fac6b.png)

I'm looking at a way to fix this, but I haven't found a good solution yet. I've looked at changing `render-string` in `color.lisp`, but it seems strange to check for something in a contrib module in a core file. Any pointers or help would be greatly appreciated.

**Comment by dbjergaard** [comment] 2015-01-29 19:46
Hmm, the issue is that stumptray reserves part of the modeline for itself but the modeline doesn't realize that stumptray has reserved the space.  A fix for this iteration of the modeline would be modifying the special '^>' instruction to correct for the width of stumptray.  Ideally this would be done from stumptray (by redefining the relevant part of the modeline formatter) but I doubt it will be so straightforward.  More likely you'll need some vars in stumpwm that you can use from stumptray to communicate how wide the modeline formatter should right justify things.  Let me know if this make sense.

**Comment by ryuslash** [comment] 2015-02-08 19:51
Yes, but it seems rather crude to just add a variable `mode-line-right-margin` or anything similar. There should be a somewhat more general way to tell the mode-line that a part of it is reserved for something else.

**Closed** 2016-12-12 16:29 UTC

**Comment by z3t0** [comment] 2019-04-20 08:34
I have tried using the solution described in #56 but it seems that in my case the modeline isnt leaving any placeholder space.

I'll debug further and post what I find, but was wondering if this solution is working for everyone?
